# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 3.6

    - os: osx
      python: 3.6

cache: pip

before_install:
  - uname -a
  - df -h
  - ulimit -a
  - ccache -s
  - which python; python --version
  - pip install --upgrade pip
  - pip install --upgrade wheel
  # Set numpy version first, other packages link against it
  - pip install fbs PyQt5==5.9.2 PyInstaller==3.4 beem cryptography

script:
 - fbs installer
