# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 0, 0, 1, 1)
        self.autoRefreshCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.autoRefreshCheckBox.setFont(font)
        self.autoRefreshCheckBox.setObjectName("autoRefreshCheckBox")
        self.gridLayout_12.addWidget(self.autoRefreshCheckBox, 2, 0, 1, 1)
        self.refreshPushButton = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.refreshPushButton.setFont(font)
        self.refreshPushButton.setObjectName("refreshPushButton")
        self.gridLayout_12.addWidget(self.refreshPushButton, 3, 0, 1, 1)
        self.accountLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountLineEdit.sizePolicy().hasHeightForWidth())
        self.accountLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.accountLineEdit.setFont(font)
        self.accountLineEdit.setObjectName("accountLineEdit")
        self.gridLayout_12.addWidget(self.accountLineEdit, 1, 0, 1, 1)
        self.loadingProgressBar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadingProgressBar.sizePolicy().hasHeightForWidth())
        self.loadingProgressBar.setSizePolicy(sizePolicy)
        self.loadingProgressBar.setMaximum(1000)
        self.loadingProgressBar.setProperty("value", 1)
        self.loadingProgressBar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.loadingProgressBar.setInvertedAppearance(False)
        self.loadingProgressBar.setObjectName("loadingProgressBar")
        self.gridLayout_12.addWidget(self.loadingProgressBar, 4, 0, 1, 1)
        self.loadingBlocksProgressBar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadingBlocksProgressBar.sizePolicy().hasHeightForWidth())
        self.loadingBlocksProgressBar.setSizePolicy(sizePolicy)
        self.loadingBlocksProgressBar.setMinimum(0)
        self.loadingBlocksProgressBar.setMaximum(420000)
        self.loadingBlocksProgressBar.setProperty("value", 3000)
        self.loadingBlocksProgressBar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.loadingBlocksProgressBar.setObjectName("loadingBlocksProgressBar")
        self.gridLayout_12.addWidget(self.loadingBlocksProgressBar, 5, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.accountInfoGroupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountInfoGroupBox.sizePolicy().hasHeightForWidth())
        self.accountInfoGroupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.accountInfoGroupBox.setFont(font)
        self.accountInfoGroupBox.setObjectName("accountInfoGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.accountInfoGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.STEEMLabel = QtWidgets.QLabel(self.accountInfoGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.STEEMLabel.setFont(font)
        self.STEEMLabel.setObjectName("STEEMLabel")
        self.horizontalLayout.addWidget(self.STEEMLabel)
        self.SBDLabel = QtWidgets.QLabel(self.accountInfoGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SBDLabel.setFont(font)
        self.SBDLabel.setObjectName("SBDLabel")
        self.horizontalLayout.addWidget(self.SBDLabel)
        self.SPLabel = QtWidgets.QLabel(self.accountInfoGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SPLabel.setFont(font)
        self.SPLabel.setObjectName("SPLabel")
        self.horizontalLayout.addWidget(self.SPLabel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 7, 0, 1, 2)
        self.votePowerLabel = QtWidgets.QLabel(self.accountInfoGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.votePowerLabel.sizePolicy().hasHeightForWidth())
        self.votePowerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.votePowerLabel.setFont(font)
        self.votePowerLabel.setObjectName("votePowerLabel")
        self.gridLayout_2.addWidget(self.votePowerLabel, 0, 0, 1, 2)
        self.RCProgressBar = QtWidgets.QProgressBar(self.accountInfoGroupBox)
        self.RCProgressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RCProgressBar.sizePolicy().hasHeightForWidth())
        self.RCProgressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RCProgressBar.setFont(font)
        self.RCProgressBar.setProperty("value", 100)
        self.RCProgressBar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.RCProgressBar.setObjectName("RCProgressBar")
        self.gridLayout_2.addWidget(self.RCProgressBar, 6, 0, 1, 2)
        self.votePowerProgressBar = QtWidgets.QProgressBar(self.accountInfoGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.votePowerProgressBar.sizePolicy().hasHeightForWidth())
        self.votePowerProgressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.votePowerProgressBar.setFont(font)
        self.votePowerProgressBar.setProperty("value", 24)
        self.votePowerProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.votePowerProgressBar.setObjectName("votePowerProgressBar")
        self.gridLayout_2.addWidget(self.votePowerProgressBar, 1, 0, 1, 2)
        self.downvotePowerLabel = QtWidgets.QLabel(self.accountInfoGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downvotePowerLabel.sizePolicy().hasHeightForWidth())
        self.downvotePowerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.downvotePowerLabel.setFont(font)
        self.downvotePowerLabel.setObjectName("downvotePowerLabel")
        self.gridLayout_2.addWidget(self.downvotePowerLabel, 2, 0, 1, 2)
        self.RCLabel = QtWidgets.QLabel(self.accountInfoGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RCLabel.sizePolicy().hasHeightForWidth())
        self.RCLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RCLabel.setFont(font)
        self.RCLabel.setObjectName("RCLabel")
        self.gridLayout_2.addWidget(self.RCLabel, 5, 0, 1, 1)
        self.downvotePowerProgressBar = QtWidgets.QProgressBar(self.accountInfoGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downvotePowerProgressBar.sizePolicy().hasHeightForWidth())
        self.downvotePowerProgressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.downvotePowerProgressBar.setFont(font)
        self.downvotePowerProgressBar.setProperty("value", 24)
        self.downvotePowerProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.downvotePowerProgressBar.setTextVisible(True)
        self.downvotePowerProgressBar.setInvertedAppearance(False)
        self.downvotePowerProgressBar.setObjectName("downvotePowerProgressBar")
        self.gridLayout_2.addWidget(self.downvotePowerProgressBar, 3, 0, 1, 2)
        self.gridLayout_9.addWidget(self.accountInfoGroupBox, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.text2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text2.sizePolicy().hasHeightForWidth())
        self.text2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text2.setFont(font)
        self.text2.setObjectName("text2")
        self.gridLayout_10.addWidget(self.text2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 0, 2, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.rewardTableWidget = QtWidgets.QTableWidget(self.tab_7)
        self.rewardTableWidget.setObjectName("rewardTableWidget")
        self.rewardTableWidget.setColumnCount(7)
        self.rewardTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout_13.addWidget(self.rewardTableWidget, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame = QtWidgets.QFrame(self.tab_8)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.text = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.gridLayout_3.addWidget(self.text, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_2.addTab(self.tab_11, "")
        self.gridLayout_9.addWidget(self.tabWidget_2, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_5.addItem(spacerItem1, 3, 0, 1, 1)
        self.accountHistDayListWidget = QtWidgets.QListWidget(self.frame_3)
        self.accountHistDayListWidget.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountHistDayListWidget.sizePolicy().hasHeightForWidth())
        self.accountHistDayListWidget.setSizePolicy(sizePolicy)
        self.accountHistDayListWidget.setMaximumSize(QtCore.QSize(120, 16777215))
        self.accountHistDayListWidget.setObjectName("accountHistDayListWidget")
        item = QtWidgets.QListWidgetItem()
        self.accountHistDayListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.accountHistDayListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.accountHistDayListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.accountHistDayListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.accountHistDayListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.accountHistDayListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.accountHistDayListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.accountHistDayListWidget.addItem(item)
        self.gridLayout_5.addWidget(self.accountHistDayListWidget, 2, 0, 1, 1)
        self.accountHistNotificationCheckBox = QtWidgets.QCheckBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountHistNotificationCheckBox.sizePolicy().hasHeightForWidth())
        self.accountHistNotificationCheckBox.setSizePolicy(sizePolicy)
        self.accountHistNotificationCheckBox.setObjectName("accountHistNotificationCheckBox")
        self.gridLayout_5.addWidget(self.accountHistNotificationCheckBox, 1, 0, 1, 1)
        self.accountHistoryLabel = QtWidgets.QLabel(self.frame_3)
        self.accountHistoryLabel.setObjectName("accountHistoryLabel")
        self.gridLayout_5.addWidget(self.accountHistoryLabel, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.accountHistTableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.accountHistTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.accountHistTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.accountHistTableWidget.setAlternatingRowColors(True)
        self.accountHistTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.accountHistTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.accountHistTableWidget.setRowCount(0)
        self.accountHistTableWidget.setColumnCount(5)
        self.accountHistTableWidget.setObjectName("accountHistTableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.accountHistTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountHistTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountHistTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountHistTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountHistTableWidget.setHorizontalHeaderItem(4, item)
        self.accountHistTableWidget.horizontalHeader().setVisible(False)
        self.accountHistTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.accountHistTableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.accountHistTableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.accountHistTableWidget, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_4, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.blockCountLabel = QtWidgets.QLabel(self.tab_4)
        self.blockCountLabel.setGeometry(QtCore.QRect(20, 30, 120, 21))
        self.blockCountLabel.setObjectName("blockCountLabel")
        self.blockOpsTableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.blockOpsTableWidget.setGeometry(QtCore.QRect(120, 20, 398, 489))
        self.blockOpsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.blockOpsTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.blockOpsTableWidget.setRowCount(0)
        self.blockOpsTableWidget.setColumnCount(5)
        self.blockOpsTableWidget.setObjectName("blockOpsTableWidget")
        self.blockOpsTableWidget.horizontalHeader().setVisible(False)
        self.blockOpsTableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.blockOpsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.tab_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.feedNotificationCheckBox = QtWidgets.QCheckBox(self.splitter)
        self.feedNotificationCheckBox.setEnabled(False)
        self.feedNotificationCheckBox.setChecked(True)
        self.feedNotificationCheckBox.setObjectName("feedNotificationCheckBox")
        self.feedListWidget = QtWidgets.QListWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feedListWidget.sizePolicy().hasHeightForWidth())
        self.feedListWidget.setSizePolicy(sizePolicy)
        self.feedListWidget.setObjectName("feedListWidget")
        self.gridLayout_4.addWidget(self.splitter, 1, 0, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.authorLabel = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorLabel.sizePolicy().hasHeightForWidth())
        self.authorLabel.setSizePolicy(sizePolicy)
        self.authorLabel.setObjectName("authorLabel")
        self.gridLayout_6.addWidget(self.authorLabel, 0, 0, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_6.addWidget(self.titleLabel, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 1, 1, 1)
        self.webview = WebView(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webview.sizePolicy().hasHeightForWidth())
        self.webview.setSizePolicy(sizePolicy)
        self.webview.setObjectName("webview")
        self.gridLayout_4.addWidget(self.webview, 2, 1, 1, 1)
        self.commentsTreeWidget = QtWidgets.QTreeWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentsTreeWidget.sizePolicy().hasHeightForWidth())
        self.commentsTreeWidget.setSizePolicy(sizePolicy)
        self.commentsTreeWidget.setAlternatingRowColors(True)
        self.commentsTreeWidget.setAutoExpandDelay(0)
        self.commentsTreeWidget.setWordWrap(True)
        self.commentsTreeWidget.setObjectName("commentsTreeWidget")
        self.commentsTreeWidget.header().setCascadingSectionResizes(True)
        self.gridLayout_4.addWidget(self.commentsTreeWidget, 3, 0, 1, 2)
        self.auhorpermLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.auhorpermLineEdit.setObjectName("auhorpermLineEdit")
        self.gridLayout_4.addWidget(self.auhorpermLineEdit, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAccount = QtWidgets.QMenu(self.menubar)
        self.menuAccount.setObjectName("menuAccount")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionadd = QtWidgets.QAction(MainWindow)
        self.actionadd.setObjectName("actionadd")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.menuAbout.addAction(self.actionOptions)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAccount.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HiveDesktop"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings"))
        self.label_3.setText(_translate("MainWindow", "account"))
        self.autoRefreshCheckBox.setText(_translate("MainWindow", "Auto refresh"))
        self.refreshPushButton.setText(_translate("MainWindow", "Refresh"))
        self.loadingProgressBar.setFormat(_translate("MainWindow", "%v  entries"))
        self.loadingBlocksProgressBar.setFormat(_translate("MainWindow", "%v blocks"))
        self.accountInfoGroupBox.setTitle(_translate("MainWindow", "username (70)"))
        self.STEEMLabel.setText(_translate("MainWindow", "TextLabel"))
        self.SBDLabel.setText(_translate("MainWindow", "TextLabel"))
        self.SPLabel.setText(_translate("MainWindow", "TextLabel"))
        self.votePowerLabel.setText(_translate("MainWindow", "Vote Power"))
        self.RCProgressBar.setFormat(_translate("MainWindow", "%p% full in 0 hours"))
        self.downvotePowerLabel.setText(_translate("MainWindow", "DownVote Power"))
        self.RCLabel.setText(_translate("MainWindow", "RC"))
        self.groupBox.setTitle(_translate("MainWindow", "Rewards"))
        self.text2.setText(_translate("MainWindow", "Rewardinfo"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Stats"))
        item = self.rewardTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Rewards"))
        item = self.rewardTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Curation HP"))
        item = self.rewardTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author HP"))
        item = self.rewardTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "HIVE"))
        item = self.rewardTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "HBD"))
        item = self.rewardTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Prod. HP"))
        item = self.rewardTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Total USD"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Balances"))
        self.text.setText(_translate("MainWindow", "RcInfo"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Account details"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Witness details"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "Delegations"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("MainWindow", "Followers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Account info"))
        __sortingEnabled = self.accountHistDayListWidget.isSortingEnabled()
        self.accountHistDayListWidget.setSortingEnabled(False)
        item = self.accountHistDayListWidget.item(0)
        item.setText(_translate("MainWindow", "Today"))
        item = self.accountHistDayListWidget.item(1)
        item.setText(_translate("MainWindow", "Yesterday"))
        item = self.accountHistDayListWidget.item(2)
        item.setText(_translate("MainWindow", "2 Days ago"))
        item = self.accountHistDayListWidget.item(3)
        item.setText(_translate("MainWindow", "3 Days ago"))
        item = self.accountHistDayListWidget.item(4)
        item.setText(_translate("MainWindow", "4 Days ago"))
        item = self.accountHistDayListWidget.item(5)
        item.setText(_translate("MainWindow", "5 Days ago"))
        item = self.accountHistDayListWidget.item(6)
        item.setText(_translate("MainWindow", "6 Days ago"))
        item = self.accountHistDayListWidget.item(7)
        item.setText(_translate("MainWindow", "7 Days ago"))
        self.accountHistDayListWidget.setSortingEnabled(__sortingEnabled)
        self.accountHistNotificationCheckBox.setText(_translate("MainWindow", "Notifications"))
        self.accountHistoryLabel.setText(_translate("MainWindow", "0 entries"))
        self.accountHistTableWidget.setSortingEnabled(False)
        item = self.accountHistTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "type"))
        item = self.accountHistTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.accountHistTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.accountHistTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.accountHistTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "timestamp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Account Operations"))
        self.blockCountLabel.setText(_translate("MainWindow", "0 blocks"))
        self.blockOpsTableWidget.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Blocks"))
        self.feedNotificationCheckBox.setText(_translate("MainWindow", "Notification on all events"))
        self.authorLabel.setText(_translate("MainWindow", "TextLabel"))
        self.titleLabel.setText(_translate("MainWindow", "TextLabel"))
        self.commentsTreeWidget.headerItem().setText(0, _translate("MainWindow", "Author"))
        self.commentsTreeWidget.headerItem().setText(1, _translate("MainWindow", "Comment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Feed"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuAccount.setTitle(_translate("MainWindow", "Account"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionadd.setText(_translate("MainWindow", "add"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
from hivedesktop.widgets.webview import WebView
